In [2]:
import pandas as pd
import numpy as np

data = {
    'player': ['Ahmed', 'Bilal', 'Usman', 'Hamza', 'Zain', 'Faisal'],
    'position': ['Forward', 'Midfielder', 'Defender', 'Forward', 'Goalkeeper', 'Defender'],
    'goals': [12, 5, np.nan, 8, 0, np.nan],       # np.nan = missing value marker
    'age': [24, np.nan, 27, 22, 29, 25],
    'matches_played': [30, 28, 30, np.nan, 25, 30]
}

df = pd.DataFrame(data)   # dict keys become column names, values become the column data
print(df)

   player    position  goals   age  matches_played
0   Ahmed     Forward   12.0  24.0            30.0
1   Bilal  Midfielder    5.0   NaN            28.0
2   Usman    Defender    NaN  27.0            30.0
3   Hamza     Forward    8.0  22.0             NaN
4    Zain  Goalkeeper    0.0  29.0            25.0
5  Faisal    Defender    NaN  25.0            30.0

Now let's actually find those missing spots:

In [3]:
df.isnull().sum()      # count missing values per column

player            0
position          0
goals             2
age               1
matches_played    1
dtype: int64

In [4]:
(df.isnull().sum() / len(df)) * 100      # % missing per column

player             0.000000
position           0.000000
goals             33.333333
age               16.666667
matches_played    16.666667
dtype: float64

Increase difficulty — combine it with the Boolean masking you learned on Day 19, to show only the columns that actually have missing data:

In [5]:
missing = df.isnull().sum()
missing[missing > 0]

goals             2
age               1
matches_played    1
dtype: int64

Using the same df, write one line of code that shows the percentage of missing values per column, rounded to 1 decimal place.

(Hint: you already have the percentage formula above — you just need to round it. Give it a shot before I show the next concept.)

In [6]:
roundof = np.round((df.isnull().sum() / len(df)) * 100,1)
print(roundof)

player             0.0
position           0.0
goals             33.3
age               16.7
matches_played    16.7
dtype: float64

 Dropping Missing Values

In [7]:
df.dropna()  # nan anywhere drop it

  player    position  goals   age  matches_played
0  Ahmed     Forward   12.0  24.0            30.0
4   Zain  Goalkeeper    0.0  29.0            25.0

This is where thresh and subset come in — controlled cuts instead of dropping the whole squad:

In [8]:
df.dropna(thresh=4)              # keep row if it has at least 4 non-null values
df.dropna(subset=['goals'])      # only check the 'goals' column for missing values

  player    position  goals   age  matches_played
0  Ahmed     Forward   12.0  24.0            30.0
1  Bilal  Midfielder    5.0   NaN            28.0
3  Hamza     Forward    8.0  22.0             NaN
4   Zain  Goalkeeper    0.0  29.0            25.0

In [9]:
df.dropna(axis=1, thresh=5)      # drop any COLUMN with fewer than 5 non-null values

   player    position   age  matches_played
0   Ahmed     Forward  24.0            30.0
1   Bilal  Midfielder   NaN            28.0
2   Usman    Defender  27.0            30.0
3   Hamza     Forward  22.0             NaN
4    Zain  Goalkeeper  29.0            25.0
5  Faisal    Defender  25.0            30.0

Write one line of code on the same df that drops rows where age is missing, but ignores missing values in every other column.

In [10]:
df.dropna(subset=['age'])

   player    position  goals   age  matches_played
0   Ahmed     Forward   12.0  24.0            30.0
2   Usman    Defender    NaN  27.0            30.0
3   Hamza     Forward    8.0  22.0             NaN
4    Zain  Goalkeeper    0.0  29.0            25.0
5  Faisal    Defender    NaN  25.0            30.0

 Filling Missing Values

In [11]:
df['goals'].fillna(df['goals'].mean())

0    12.00
1     5.00
2     6.25
3     8.00
4     0.00
5     6.25
Name: goals, dtype: float64

In [12]:
df['age'].fillna(df['age'].median())        # median — better when outliers exist

0    24.0
1    25.0
2    27.0
3    22.0
4    29.0
5    25.0
Name: age, dtype: float64

In [13]:
df['position'].fillna(df['position'].mode()[0])

0       Forward
1    Midfielder
2      Defender
3       Forward
4    Goalkeeper
5      Defender
Name: position, dtype: object

In [14]:
df['goals'].fillna(method='ffill')      # copies the previous row's value into the gap

/tmp/ipykernel_4478/777893409.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['goals'].fillna(method='ffill')      # copies the previous row's value into the gap

0    12.0
1     5.0
2     5.0
3     8.0
4     0.0
5     0.0
Name: goals, dtype: float64

In [15]:
df.fillna({'goals': df['goals'].mean(), 'age': df['age'].median(), 'position': df['position'].mode()[0]})

   player    position  goals   age  matches_played
0   Ahmed     Forward  12.00  24.0            30.0
1   Bilal  Midfielder   5.00  25.0            28.0
2   Usman    Defender   6.25  27.0            30.0
3   Hamza     Forward   8.00  22.0             NaN
4    Zain  Goalkeeper   0.00  29.0            25.0
5  Faisal    Defender   6.25  25.0            30.0

Write one line that fills the missing matches_played values with the median of that column.

In [16]:
df['matches_played'].fillna(df['matches_played'].median())

0    30.0
1    28.0
2    30.0
3    30.0
4    25.0
5    30.0
Name: matches_played, dtype: float64

In [17]:
data2 = {
    'player': ['Ahmed', 'Bilal', 'Usman', 'Ahmed', 'Zain'],
    'position': ['Forward', 'Midfielder', 'Defender', 'Forward', 'Goalkeeper'],
    'goals': [12, 5, 3, 12, 0]
}
df2 = pd.DataFrame(data2)
print(df2)

  player    position  goals
0  Ahmed     Forward     12
1  Bilal  Midfielder      5
2  Usman    Defender      3
3  Ahmed     Forward     12
4   Zain  Goalkeeper      0

In [18]:
df2.duplicated()      # returns True/False per row — True means "this exact row appeared earlier"

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [19]:
df2.drop_duplicates()      # keeps first occurrence, drops the rest

  player    position  goals
0  Ahmed     Forward     12
1  Bilal  Midfielder      5
2  Usman    Defender      3
4   Zain  Goalkeeper      0

In [20]:
df2.duplicated(subset=['player'])          # flag by player name only, ignore other columns
df2.drop_duplicates(subset=['player'], keep='last')   # keep the LAST entry per player instead of first

  player    position  goals
1  Bilal  Midfielder      5
2  Usman    Defender      3
3  Ahmed     Forward     12
4   Zain  Goalkeeper      0

In [21]:
df2.duplicated().sum()      # total number of duplicate rows

np.int64(1)

Using df2, write one line that checks for duplicates based only on the player column, keeping the last occurrence as the non-duplicate.

In [22]:
df2.duplicated(subset=['player'],keep='last')

0     True
1    False
2    False
3    False
4    False
dtype: bool

In [23]:
# Goal: fill missing 'age' values with the column's median
# Add parentheses to call the method
df['age'] = df['age'].fillna(df['age'].median())
print(df['age'])

0    24.0
1    25.0
2    27.0
3    22.0
4    29.0
5    25.0
Name: age, dtype: float64

In [24]:
# Goal: remove exact duplicate rows from df2, checking the whole row
df2.drop_duplicates(subset=['player', 'position', 'goals'])

  player    position  goals
0  Ahmed     Forward     12
1  Bilal  Midfielder      5
2  Usman    Defender      3
4   Zain  Goalkeeper      0

In [25]:
# Goal: keep only rows where 'goals' is NOT missing
# Save the result back to df
df = df.dropna(subset=['goals'])
print(df)

  player    position  goals   age  matches_played
0  Ahmed     Forward   12.0  24.0            30.0
1  Bilal  Midfielder    5.0  25.0            28.0
3  Hamza     Forward    8.0  22.0             NaN
4   Zain  Goalkeeper    0.0  29.0            25.0

Challenge 1 (Beginner):
Using the original df (before any of today's cleaning — recreate it if needed, all 5 columns, 6 players), write one line to find the total number of missing values in the entire DataFrame (not per column — one single number).

In [26]:
data = {
    'player': ['Ahmed', 'Bilal', 'Usman', 'Hamza', 'Zain', 'Faisal'],
    'position': ['Forward', 'Midfielder', 'Defender', 'Forward', 'Goalkeeper', 'Defender'],
    'goals': [12, 5, np.nan, 8, 0, np.nan],       # np.nan = missing value marker
    'age': [24, np.nan, 27, 22, 29, 25],
    'matches_played': [30, 28, 30, np.nan, 25, 30]
}

df = pd.DataFrame(data)   # dict keys become column names, values become the column data
print(df)
df.isnull().sum().sum()

   player    position  goals   age  matches_played
0   Ahmed     Forward   12.0  24.0            30.0
1   Bilal  Midfielder    5.0   NaN            28.0
2   Usman    Defender    NaN  27.0            30.0
3   Hamza     Forward    8.0  22.0             NaN
4    Zain  Goalkeeper    0.0  29.0            25.0
5  Faisal    Defender    NaN  25.0            30.0

np.int64(4)

Challenge 2 (Beginner):
Using the same fresh df, write one line to fill missing goals values with 0 (imagine: a missing goals record actually means the player just didn't score that season, not that the data is broken).

In [27]:
df['goals'].fillna(0)      # 0 is a hardcoded value, not a computed one — no .mean()/.median()/.mode() needed

0    12.0
1     5.0
2     0.0
3     8.0
4     0.0
5     0.0
Name: goals, dtype: float64

Challenge 3 (Intermediate):
Using the same fresh df, in one line, drop any row that is missing both age AND matches_played (i.e. only drop if both of those two specific columns are empty in that row — a row missing just one of them should survive).
(Hint: you'll need subset to limit which columns get checked, and one of the two how options from the anatomy line taught earlier — 'any' vs 'all'.)

In [28]:
df.dropna(subset=['age','matches_played'],how='all')

   player    position  goals   age  matches_played
0   Ahmed     Forward   12.0  24.0            30.0
1   Bilal  Midfielder    5.0   NaN            28.0
2   Usman    Defender    NaN  27.0            30.0
3   Hamza     Forward    8.0  22.0             NaN
4    Zain  Goalkeeper    0.0  29.0            25.0
5  Faisal    Defender    NaN  25.0            30.0

In [29]:
import pandas as pd
import numpy as np

np.random.seed(42)                      # same seed you've used since Phase 1 — reproducible data

data = {
    "player":          ["Ali Raza", "Hamza Khan", "Bilal Ahmed", "Usman Tariq", "Ahmed Zafar",
                         "Zain Malik", "Hamza Khan", "Omar Farooq", "Danish Iqbal", "Salman Butt"],
    "position":        ["FW", "MF", "DF", "GK", "FW", "MF", "MF", np.nan, "DF", "FW"],
    "age":             [24, 27, np.nan, 29, 22, np.nan, 27, 31, 26, np.nan],
    "goals":           [14, 6, 1, 0, 9, 3, 6, 2, 0, 11],
    "market_value_k":  [850, np.nan, 300, 400, np.nan, 275, np.nan, 190, 310, 720]
}

df = pd.DataFrame(data)
print(df)

         player position   age  goals  market_value_k
0      Ali Raza       FW  24.0     14           850.0
1    Hamza Khan       MF  27.0      6             NaN
2   Bilal Ahmed       DF   NaN      1           300.0
3   Usman Tariq       GK  29.0      0           400.0
4   Ahmed Zafar       FW  22.0      9             NaN
5    Zain Malik       MF   NaN      3           275.0
6    Hamza Khan       MF  27.0      6             NaN
7   Omar Farooq      NaN  31.0      2           190.0
8  Danish Iqbal       DF  26.0      0           310.0
9   Salman Butt       FW   NaN     11           720.0

In [30]:
df.isnull()          # returns a same-shape DataFrame of True/False — True = missing
df.isnull().sum()    # chains .sum() on top — adds up the Trues (True=1) per column

player            0
position          1
age               3
goals             0
market_value_k    3
dtype: int64

In [31]:
missing_pct = (df.isnull().sum() / len(df)) * 100   # len(df) = total row count = 10
print(missing_pct)

player             0.0
position          10.0
age               30.0
goals              0.0
market_value_k    30.0
dtype: float64

In [32]:
df.isnull().sum(axis=1)   # axis=1 flips direction: sum ACROSS each row instead of down each column

0    0
1    1
2    1
3    0
4    1
5    1
6    1
7    1
8    0
9    1
dtype: int64

Using the same df, write the code yourself (don't just read — type it out) to answer this:
Which column has the highest percentage of missing data, and what is that percentage?
You can reuse the missing_pct line above — just add one thing to it to pull out the highest value automatically instead of reading it by eye. Give it a shot and send me your code.

In [33]:
new_percentage = (df.isnull().sum()/len(df)) * 100
print(new_percentage)  # the age and maket value has the highest percentage

player             0.0
position          10.0
age               30.0
goals              0.0
market_value_k    30.0
dtype: float64

In [34]:
print(df.isnull().sum())

player            0
position          1
age               3
goals             0
market_value_k    3
dtype: int64

[Ledger: isnull(), sum(), missing % calc, column selection from Day 20]
Using missing_pct from above, print just the position and market_value_k values from it — not the whole Series. You already know how to select multiple columns by name from Day 20 (df[['c1','c2']]) — the same square-bracket-with-a-list trick works on a Series too.

In [35]:
print(missing_pct[['position','market_value_k']])

position          10.0
market_value_k    30.0
dtype: float64

In [36]:
df.dropna()                          # drops any row that has AT LEAST ONE missing value, in any column
df.dropna(subset=["position"])       # only checks the "position" column — drops a row ONLY if position is missing
df.dropna(thresh=4)                  # keeps a row only if it has at least 4 non-missing values (out of 5 columns)

         player position   age  goals  market_value_k
0      Ali Raza       FW  24.0     14           850.0
1    Hamza Khan       MF  27.0      6             NaN
2   Bilal Ahmed       DF   NaN      1           300.0
3   Usman Tariq       GK  29.0      0           400.0
4   Ahmed Zafar       FW  22.0      9             NaN
5    Zain Malik       MF   NaN      3           275.0
6    Hamza Khan       MF  27.0      6             NaN
7   Omar Farooq      NaN  31.0      2           190.0
8  Danish Iqbal       DF  26.0      0           310.0
9   Salman Butt       FW   NaN     11           720.0

In [37]:
df.dropna(subset=["position", "age"], thresh=None)   # drop a row only if BOTH position AND age would need thresh logic...

Empty DataFrame
Columns: [player, position, age, goals, market_value_k]
Index: []

In [38]:
df.dropna(subset=["position", "age"])   # drop a row if EITHER position OR age is missing (checks both columns)

         player position   age  goals  market_value_k
0      Ali Raza       FW  24.0     14           850.0
1    Hamza Khan       MF  27.0      6             NaN
3   Usman Tariq       GK  29.0      0           400.0
4   Ahmed Zafar       FW  22.0      9             NaN
6    Hamza Khan       MF  27.0      6             NaN
8  Danish Iqbal       DF  26.0      0           310.0

In [39]:
df.dropna(axis=1)   # axis=1 drops COLUMNS instead of rows — any column with a single NaN gets removed entirely

         player  goals
0      Ali Raza     14
1    Hamza Khan      6
2   Bilal Ahmed      1
3   Usman Tariq      0
4   Ahmed Zafar      9
5    Zain Malik      3
6    Hamza Khan      6
7   Omar Farooq      2
8  Danish Iqbal      0
9   Salman Butt     11

Write one line that drops a row only if market_value_k is missing — keep everyone else, even if they're missing position or age.

In [40]:
df.dropna(subset=['market_value_k'])

         player position   age  goals  market_value_k
0      Ali Raza       FW  24.0     14           850.0
2   Bilal Ahmed       DF   NaN      1           300.0
3   Usman Tariq       GK  29.0      0           400.0
5    Zain Malik       MF   NaN      3           275.0
7   Omar Farooq      NaN  31.0      2           190.0
8  Danish Iqbal       DF  26.0      0           310.0
9   Salman Butt       FW   NaN     11           720.0

In [41]:
df["age"].fillna(df["age"].mean())      # fill missing age with the AVERAGE age of the whole column

0    24.000000
1    27.000000
2    26.571429
3    29.000000
4    22.000000
5    26.571429
6    27.000000
7    31.000000
8    26.000000
9    26.571429
Name: age, dtype: float64

In [42]:
df["age"].fillna(df["age"].median())

0    24.0
1    27.0
2    27.0
3    29.0
4    22.0
5    27.0
6    27.0
7    31.0
8    26.0
9    27.0
Name: age, dtype: float64

In [43]:
df["position"].fillna(df["position"].mode()[0])

0    FW
1    MF
2    DF
3    GK
4    FW
5    MF
6    MF
7    FW
8    DF
9    FW
Name: position, dtype: object

Fill the missing age values using the median instead of the mean, and actually save it back into df["age"] (don't just print it). Write the full line.

In [44]:
df['age'] = df['age'].fillna(df['age'].median())
print(df['age'])

0    24.0
1    27.0
2    27.0
3    29.0
4    22.0
5    27.0
6    27.0
7    31.0
8    26.0
9    27.0
Name: age, dtype: float64

In [45]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool

In [46]:
df.duplicated().sum()

np.int64(1)

In [47]:
df.drop_duplicates()

         player position   age  goals  market_value_k
0      Ali Raza       FW  24.0     14           850.0
1    Hamza Khan       MF  27.0      6             NaN
2   Bilal Ahmed       DF  27.0      1           300.0
3   Usman Tariq       GK  29.0      0           400.0
4   Ahmed Zafar       FW  22.0      9             NaN
5    Zain Malik       MF  27.0      3           275.0
7   Omar Farooq      NaN  31.0      2           190.0
8  Danish Iqbal       DF  26.0      0           310.0
9   Salman Butt       FW  27.0     11           720.0

In [48]:
df.drop_duplicates(subset=["player"], keep="last")   # dedupe by player NAME only, keep the LAST filed report

         player position   age  goals  market_value_k
0      Ali Raza       FW  24.0     14           850.0
2   Bilal Ahmed       DF  27.0      1           300.0
3   Usman Tariq       GK  29.0      0           400.0
4   Ahmed Zafar       FW  22.0      9             NaN
5    Zain Malik       MF  27.0      3           275.0
6    Hamza Khan       MF  27.0      6             NaN
7   Omar Farooq      NaN  31.0      2           190.0
8  Danish Iqbal       DF  26.0      0           310.0
9   Salman Butt       FW  27.0     11           720.0

Write one line that removes the duplicate Hamza Khan row, but this time keep his first filed report (row 1, not row 6) — using subset on player explicitly, even though it's the default behavior here.

In [49]:
df.drop_duplicates(subset=['player'],keep='first')

         player position   age  goals  market_value_k
0      Ali Raza       FW  24.0     14           850.0
1    Hamza Khan       MF  27.0      6             NaN
2   Bilal Ahmed       DF  27.0      1           300.0
3   Usman Tariq       GK  29.0      0           400.0
4   Ahmed Zafar       FW  22.0      9             NaN
5    Zain Malik       MF  27.0      3           275.0
7   Omar Farooq      NaN  31.0      2           190.0
8  Danish Iqbal       DF  26.0      0           310.0
9   Salman Butt       FW  27.0     11           720.0