In [15]:
import pandas as pd

orders_df = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105, 106, 107, 108],
    'customer_name': [' ali khan', 'SARA-ahmed', 'bilal   raza', 'Hina-Fatima',
                       'zain ul abdin', ' Mariam-Noor', 'ahsan  javed', 'NIDA-KHAN'],
    'price': [450, 1200, 300, 2500, 800, 150, 3200, 600],
    'product': ['Cappuccino', 'Espresso Combo', 'Latte', 'Family Pack',
                'Mocha', 'Tea', 'Premium Bundle', 'Americano']
})
orders_df

   order_id  customer_name  price         product
0       101       ali khan    450      Cappuccino
1       102     SARA-ahmed   1200  Espresso Combo
2       103   bilal   raza    300           Latte
3       104    Hina-Fatima   2500     Family Pack
4       105  zain ul abdin    800           Mocha
5       106    Mariam-Noor    150             Tea
6       107   ahsan  javed   3200  Premium Bundle
7       108      NIDA-KHAN    600       Americano

In [16]:
status_map = {101: "paid", 102: "paid", 103: "pending"}   # dict: key=order_id, value=status

orders_df['order_id'].map(status_map)   # looks up each order_id in the dict

0       paid
1       paid
2    pending
3        NaN
4        NaN
5        NaN
6        NaN
7        NaN
Name: order_id, dtype: object

Using orders_df['product'], build a dict that maps 'Tea' → 'hot drink', 'Cappuccino' → 'hot drink', 'Mocha' → 'hot drink', and use .map() to create the mapping. Don't worry about the other products — see what happens to them.

In [17]:
status_drinks = {"Tea":"hot drink" , "Cappuccino":"hot drink" , "Mocha":"hot drink"}
orders_df['product'].map(status_drinks)

0    hot drink
1          NaN
2          NaN
3          NaN
4    hot drink
5    hot drink
6          NaN
7          NaN
Name: product, dtype: object

In [18]:
orders_df['price'].apply(lambda x: x * 2 if x > 1000 else x)
# lambda x: ...       -> a mini function, x = one price value at a time
# x * 2 if x > 1000 else x   -> double it if price > 1000, otherwise leave unchanged

0     450
1    2400
2     300
3    5000
4     800
5     150
6    6400
7     600
Name: price, dtype: int64

Write orders_df['price'].apply(lambda x: "expensive" if x > 1000 else "cheap") yourself and check the output makes sense against the actual prices.

In [19]:
orders_df['price'].apply(lambda x : "expensive" if x > 1000 else "cheap")

0        cheap
1    expensive
2        cheap
3    expensive
4        cheap
5        cheap
6    expensive
7        cheap
Name: price, dtype: object

In [20]:
def price_tier(row):                 # row = one full row of the DataFrame, like a mini Series
    if row['price'] >= 2000:
        return "Premium"
    elif row['price'] >= 500:
        return "Standard"
    else:
        return "Budget"

orders_df['price_tier'] = orders_df.apply(price_tier, axis=1)   # axis=1 -> apply row-wise, not column-wise
orders_df

   order_id  customer_name  price         product price_tier
0       101       ali khan    450      Cappuccino     Budget
1       102     SARA-ahmed   1200  Espresso Combo   Standard
2       103   bilal   raza    300           Latte     Budget
3       104    Hina-Fatima   2500     Family Pack    Premium
4       105  zain ul abdin    800           Mocha   Standard
5       106    Mariam-Noor    150             Tea     Budget
6       107   ahsan  javed   3200  Premium Bundle    Premium
7       108      NIDA-KHAN    600       Americano   Standard

In [21]:
orders_df['is_premium'] = orders_df['price'] >= 2000   # boolean mask -> True/False column
orders_df

   order_id  customer_name  price         product price_tier  is_premium
0       101       ali khan    450      Cappuccino     Budget       False
1       102     SARA-ahmed   1200  Espresso Combo   Standard       False
2       103   bilal   raza    300           Latte     Budget       False
3       104    Hina-Fatima   2500     Family Pack    Premium        True
4       105  zain ul abdin    800           Mocha   Standard       False
5       106    Mariam-Noor    150             Tea     Budget       False
6       107   ahsan  javed   3200  Premium Bundle    Premium        True
7       108      NIDA-KHAN    600       Americano   Standard       False

Write a function discount_flag(row) that returns "discount" if row['product'] contains the word "Combo" or "Bundle", else "full price". Apply it row-wise into a new column discount_status. (Hint: you'll need string checking — which we're about to teach next, so hold this thought for one more concept.)

In [22]:
orders_df['customer_name'].str.lower()     # lowercase every value
orders_df['customer_name'].str.strip()     # remove leading/trailing spaces
orders_df['customer_name'].str.contains('khan')   # True/False: does the string contain 'khan'?

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: customer_name, dtype: bool

In [23]:
orders_df['customer_name'].str.strip().str.lower().str.split('-', expand=True)
# .strip()               -> trims stray spaces first
# .lower()                -> normalizes case
# .split('-', expand=True) -> splits on '-', returns separate columns instead of a list

               0       1
0       ali khan    None
1           sara   ahmed
2   bilal   raza    None
3           hina  fatima
4  zain ul abdin    None
5         mariam    noor
6   ahsan  javed    None
7           nida    khan

Write a function discount_flag(row) that returns "discount" if row['product'] contains the word "Combo" or "Bundle", else "full price". Apply it row-wise into a new column discount_status. (Hint: you'll need string checking — which we're about to teach next, so hold this thought for one more concept.)

In [24]:
def discount_flag(row):
    if 'Combo' in row['product'] or 'Bundle' in row['product']:
        return "discount"
    else:
        return "full price"

orders_df['discount_status'] = orders_df.apply(discount_flag, axis=1)

print(orders_df[['product', 'discount_status']])

          product discount_status
0      Cappuccino      full price
1  Espresso Combo        discount
2           Latte      full price
3     Family Pack      full price
4           Mocha      full price
5             Tea      full price
6  Premium Bundle        discount
7       Americano      full price

Chain .str.strip(), .str.lower() on customer_name, save it into a new column clean_name, then check .str.contains('khan') on that new clean column and compare to the original messy one.

In [25]:
orders_df['clean_name'] = orders_df['customer_name'].str.strip().str.lower().str.contains('khan')
orders_df

,order_id,customer_name,price,product,price_tier,is_premium,discount_status,clean_name
0,101,ali khan,450,Cappuccino,Budget,False,full price,True
1,102,SARA-ahmed,1200,Espresso Combo,Standard,False,discount,False
2,103,bilal raza,300,Latte,Budget,False,full price,False
3,104,Hina-Fatima,2500,Family Pack,Premium,True,full price,False
4,105,zain ul abdin,800,Mocha,Standard,False,full price,False
5,106,Mariam-Noor,150,Tea,Budget,False,full price,False
6,107,ahsan javed,3200,Premium Bundle,Premium,True,discount,False
7,108,NIDA-KHAN,600,Americano,Standard,False,full price,True

In [26]:
def price_tier(row):
    if row['price'] >= 2000:      # bug here
        return "Premium"
    return "Standard"
orders_df.apply(price_tier,axis=1)     # bug here too

0    Standard
1    Standard
2    Standard
3     Premium
4    Standard
5    Standard
6     Premium
7    Standard
dtype: object

In [27]:
orders_df['customer_name'].str.contains('khan')   # bug

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
Name: customer_name, dtype: bool

In [28]:
orders_df['order_id'].map(status_map)   # bug — wrong dict used

0       paid
1       paid
2    pending
3        NaN
4        NaN
5        NaN
6        NaN
7        NaN
Name: order_id, dtype: object

Map product → a dict where 'Tea' and 'Espresso Combo' map to "drink", others unmapped.

In [30]:
new_map = {'Tea':'drink','Espresso Combo':'drink'}
orders_df['product'].map(new_map)

0      NaN
1    drink
2      NaN
3      NaN
4      NaN
5    drink
6      NaN
7      NaN
Name: product, dtype: object

Use .apply(lambda x: ...) on price to flag anything under Rs. 500 as "low"

In [31]:
orders_df['price'].apply(lambda y : "low" if y < 500 else "high")

0     low
1    high
2     low
3    high
4    high
5     low
6    high
7    high
Name: price, dtype: object

Write a function that returns "bundle" if product contains "Bundle" or "Combo" (use .str.contains inside the function on row['product']), else "single item". Apply row-wise.

In [37]:
def Buncomb(row) :
  if row['product'].str.contains('Bundle') :
    return 'Bundle'
  elif row['product'].str.contains('Combo') :
    return 'Combo'
  else :
    return 'None'
orders_df['Bundle_Combo'] = orders_df.apply(Buncomb,axis=1)
orders_df

AttributeError: 'str' object has no attribute 'str'

4. Clean customer_name fully (strip + lower) and save to clean_name.

In [41]:
orders_df['clean_customer_name'] = orders_df['customer_name'].str.lower().str.strip()
orders_df

,order_id,customer_name,price,product,price_tier,is_premium,discount_status,clean_name,clean_customer_name
0,101,ali khan,450,Cappuccino,Budget,False,full price,True,ali khan
1,102,SARA-ahmed,1200,Espresso Combo,Standard,False,discount,False,sara-ahmed
2,103,bilal raza,300,Latte,Budget,False,full price,False,bilal raza
3,104,Hina-Fatima,2500,Family Pack,Premium,True,full price,False,hina-fatima
4,105,zain ul abdin,800,Mocha,Standard,False,full price,False,zain ul abdin
5,106,Mariam-Noor,150,Tea,Budget,False,full price,False,mariam-noor
6,107,ahsan javed,3200,Premium Bundle,Premium,True,discount,False,ahsan javed
7,108,NIDA-KHAN,600,Americano,Standard,False,full price,True,nida-khan

5. Filter orders_df to rows where clean_name contains "khan".

In [42]:
orders_df['clean_customer_name'].str.contains('khan')

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7     True
Name: clean_customer_name, dtype: bool

Split clean_name on '-' where possible and store first/last name in two new columns.

In [44]:
orders_df['clean_customer_name'].str.split('-',expand=True)

               0       1
0       ali khan    None
1           sara   ahmed
2   bilal   raza    None
3           hina  fatima
4  zain ul abdin    None
5         mariam    noor
6   ahsan  javed    None
7           nida    khan

Mini Project: Coffee Shop Customer Cleanup

Clean customer_name → clean_name (strip + lower).

In [45]:
orders_df['clean_customer_name'].str.strip().str.lower()

0         ali khan
1       sara-ahmed
2     bilal   raza
3      hina-fatima
4    zain ul abdin
5      mariam-noor
6     ahsan  javed
7        nida-khan
Name: clean_customer_name, dtype: object

Build price_tier with .apply(axis=1) (Premium ≥2000, Standard ≥500, Budget below).

In [47]:
def new_price_tier(row) :
  if row['price'] >= 2000 :
    return "Premium"
  elif row['price'] >= 500 :
    return "Standard"
  else :
    return "Budget Below"
orders_df['price_category'] = orders_df.apply(new_price_tier,axis=1)
orders_df

,order_id,customer_name,price,product,price_tier,is_premium,discount_status,clean_name,clean_customer_name,price_category
0,101,ali khan,450,Cappuccino,Budget,False,full price,True,ali khan,Budget Below
1,102,SARA-ahmed,1200,Espresso Combo,Standard,False,discount,False,sara-ahmed,Standard
2,103,bilal raza,300,Latte,Budget,False,full price,False,bilal raza,Budget Below
3,104,Hina-Fatima,2500,Family Pack,Premium,True,full price,False,hina-fatima,Premium
4,105,zain ul abdin,800,Mocha,Standard,False,full price,False,zain ul abdin,Standard
5,106,Mariam-Noor,150,Tea,Budget,False,full price,False,mariam-noor,Budget Below
6,107,ahsan javed,3200,Premium Bundle,Premium,True,discount,False,ahsan javed,Premium
7,108,NIDA-KHAN,600,Americano,Standard,False,full price,True,nida-khan,Standard

Add a discount_status column: "discount" if product contains "Combo" or "Bundle", else "full price".

In [48]:
def Buncomb(row):
    if 'Bundle' in row['product']:
        return 'Bundle'
    elif 'Combo' in row['product']:
        return 'Combo'
    else:
        return 'full price'

orders_df['Bundle_Combo'] = orders_df.apply(Buncomb, axis=1)
orders_df

,order_id,customer_name,price,product,price_tier,is_premium,discount_status,clean_name,clean_customer_name,price_category,Bundle_Combo
0,101,ali khan,450,Cappuccino,Budget,False,full price,True,ali khan,Budget Below,full price
1,102,SARA-ahmed,1200,Espresso Combo,Standard,False,discount,False,sara-ahmed,Standard,Combo
2,103,bilal raza,300,Latte,Budget,False,full price,False,bilal raza,Budget Below,full price
3,104,Hina-Fatima,2500,Family Pack,Premium,True,full price,False,hina-fatima,Premium,full price
4,105,zain ul abdin,800,Mocha,Standard,False,full price,False,zain ul abdin,Standard,full price
5,106,Mariam-Noor,150,Tea,Budget,False,full price,False,mariam-noor,Budget Below,full price
6,107,ahsan javed,3200,Premium Bundle,Premium,True,discount,False,ahsan javed,Premium,Bundle
7,108,NIDA-KHAN,600,Americano,Standard,False,full price,True,nida-khan,Standard,full price

Use groupby (Cumulative Ledger) to find average price per price_tier.

In [53]:
tier_avg = orders_df.groupby('price_category')['price'].mean()
# groupby('price_category')  -> group rows by the Premium/Standard/Budget label
# ['price']                  -> pick just the price column to summarize
# .mean()                    -> average price within each group

tier_avg

price_category
Budget Below     300.000000
Premium         2850.000000
Standard         866.666667
Name: price, dtype: float64