Part 1 — Day 16: Lists → Arrays, Shape, Indexing

In [107]:
import numpy as np

In [108]:
players = ["Ali", "Bilal", "Hamza", "Zain", "Sana", "Usman"]
goals_list = [9, 4, 14, 2, 7, 11]
goals = np.array(goals_list)
print(goals)

[ 9  4 14  2  7 11]

In [109]:
squad_stats = np.array([
    [9, 4, 22],[4, 8, 15],[14, 3, 30],[2, 9, 10],[7, 6, 18],[11, 2, 25]
])
print(squad_stats)

[[ 9  4 22]
 [ 4  8 15]
 [14  3 30]
 [ 2  9 10]
 [ 7  6 18]
 [11  2 25]]

In [110]:
squad_stats[2, :]     # Hamza's row (index 2)

array([14,  3, 30])

In [111]:
squad_stats[:, 1]     # everyone's assists

array([4, 8, 3, 9, 6, 2])

Part 2 — Day 17: Broadcasting, Axis, Reshape/Transpose

In [112]:
stat_bonus = np.array([1, 0, 2])   # +1 goal, +0 assist, +2 shots
final_stats = squad_stats + stat_bonus
print(final_stats)

[[10  4 24]
 [ 5  8 17]
 [15  3 32]
 [ 3  9 12]
 [ 8  6 20]
 [12  2 27]]

In [113]:
total_per_stat = squad_stats.sum(axis=0)
print(total_per_stat)

[ 47  32 120]

In [114]:
total_per_player = squad_stats.sum(axis=1)
print(total_per_player)

[35 27 47 21 31 38]

In [115]:
goals.reshape(-1, 1)     # (6,) -> (6,1)

array([[ 9],
       [ 4],
       [14],
       [ 2],
       [ 7],
       [11]])

In [116]:
squad_stats.T             # (6,3) -> (3,6)

array([[ 9,  4, 14,  2,  7, 11],
       [ 4,  8,  3,  9,  6,  2],
       [22, 15, 30, 10, 18, 25]])

Part 3 — Day 18: Dot Product, RMSE, Cosine Similarity

In [117]:
weights = np.array([3, 2, 1])   # goal=3, assist=2, shot=1
performance_score = np.dot(squad_stats, weights)
print(performance_score)

[57 43 78 34 51 62]

In [118]:
# RMSE — how far off was the coach's pre-season prediction?
predicted_goals = np.array([8, 5, 12, 3, 6, 10])   # coach's pre-season guess for each player
actual_goals = goals                                # goals is already defined from Part 1 = [9, 4, 14, 2, 7, 11]

errors = actual_goals - predicted_goals
rmse = np.sqrt(np.mean(errors ** 2))

print("Errors per player:", errors)
print("RMSE (prediction accuracy):", round(rmse, 2))

Errors per player: [ 1 -1  2 -1  1  1]
RMSE (prediction accuracy): 1.22

In [119]:
# Cosine similarity — who plays most like Hamza?
hamza = squad_stats[2]   # Hamza's row: [14, 3, 30]

for name, row in zip(players, squad_stats):
    dot = np.dot(hamza, row)
    mag_hamza = np.sqrt(np.sum(hamza**2))
    mag_row = np.sqrt(np.sum(row**2))
    similarity = dot / (mag_hamza * mag_row)
    print(f"Hamza vs {name:6s}: {similarity:.3f}")

Hamza vs Ali   : 0.996
Hamza vs Bilal : 0.913
Hamza vs Hamza : 1.000
Hamza vs Zain  : 0.785
Hamza vs Sana  : 0.976
Hamza vs Usman : 1.000

Part 4 — Day 19: Boolean Masking, np.where, Random Module

In [120]:
elite_mask = goals > 8
elite_players = np.array(players)[elite_mask]
print(elite_players)

['Ali' 'Hamza' 'Usman']

In [121]:
labels = np.where(performance_score >= 40, "Star", "Regular")
print(labels)

['Star' 'Star' 'Star' 'Regular' 'Star' 'Star']

In [122]:
np.random.seed(42)
trial_goals = np.random.randint(0, 4, size=5)
print(trial_goals)

[2 3 0 2 2]

Part 5 — Day 20: Series & DataFrame

In [123]:
import pandas as pd

In [124]:
goals_series = pd.Series(goals, index=players)
print(goals_series)

Ali       9
Bilal     4
Hamza    14
Zain      2
Sana      7
Usman    11
dtype: int64

In [125]:
squad_df = pd.DataFrame({
    "player": ["Ali","Bilal","Hamza","Zain","Sana","Usman","Zain"],
    "position": ["Forward","Midfielder","Forward",np.nan,"Defender","Forward","Defender"],
    "age": [24,27,np.nan,21,22,np.nan,21],
    "goals": [9,4,14,2,7,11,2],
    "assists": [4,8,3,9,6,2,9],
    "shots": [22,15,30,10,18,25,10]
})
print(squad_df)

  player    position   age  goals  assists  shots
0    Ali     Forward  24.0      9        4     22
1  Bilal  Midfielder  27.0      4        8     15
2  Hamza     Forward   NaN     14        3     30
3   Zain         NaN  21.0      2        9     10
4   Sana    Defender  22.0      7        6     18
5  Usman     Forward   NaN     11        2     25
6   Zain    Defender  21.0      2        9     10

In [126]:
squad_df.loc[squad_df["position"] == "Forward"]

  player position   age  goals  assists  shots
0    Ali  Forward  24.0      9        4     22
2  Hamza  Forward   NaN     14        3     30
5  Usman  Forward   NaN     11        2     25

In [127]:
squad_df.iloc[0:3]

  player    position   age  goals  assists  shots
0    Ali     Forward  24.0      9        4     22
1  Bilal  Midfielder  27.0      4        8     15
2  Hamza     Forward   NaN     14        3     30

Part 6 — Day 21: Missing Values & Duplicates

In [128]:
squad_df.isnull().sum()

player      0
position    1
age         2
goals       0
assists     0
shots       0
dtype: int64

In [129]:
squad_df["age"] = squad_df["age"].fillna(squad_df["age"].median())
print(squad_df["age"])

0    24.0
1    27.0
2    22.0
3    21.0
4    22.0
5    22.0
6    21.0
Name: age, dtype: float64

In [130]:
squad_df["position"] = squad_df["position"].fillna(squad_df["position"].mode()[0])
print(squad_df["position"])

0       Forward
1    Midfielder
2       Forward
3       Forward
4      Defender
5       Forward
6      Defender
Name: position, dtype: object

In [131]:
squad_df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [132]:
squad_df.drop_duplicates(subset=["player"], keep="first")

  player    position   age  goals  assists  shots
0    Ali     Forward  24.0      9        4     22
1  Bilal  Midfielder  27.0      4        8     15
2  Hamza     Forward  22.0     14        3     30
3   Zain     Forward  21.0      2        9     10
4   Sana    Defender  22.0      7        6     18
5  Usman     Forward  22.0     11        2     25

In [133]:
# weights was defined earlier in Part 3:
weights = np.array([3, 2, 1])   # goal=3pts, assist=2pts, shot=1pt

# clean_stats — pull the 3 numeric columns back out of squad_df as a plain array
clean_stats = squad_df[["goals", "assists", "shots"]].values

squad_df["performance_score"] = np.dot(clean_stats, weights)
squad_df["status"] = np.where(squad_df["performance_score"] >= 40, "Star", "Regular")
final_report = squad_df.sort_values("performance_score", ascending=False).reset_index(drop=True)

print(final_report)

  player    position   age  goals  assists  shots  performance_score   status
0  Hamza     Forward  22.0     14        3     30                 78     Star
1  Usman     Forward  22.0     11        2     25                 62     Star
2    Ali     Forward  24.0      9        4     22                 57     Star
3   Sana    Defender  22.0      7        6     18                 51     Star
4  Bilal  Midfielder  27.0      4        8     15                 43     Star
5   Zain     Forward  21.0      2        9     10                 34  Regular
6   Zain    Defender  21.0      2        9     10                 34  Regular