⚽ Day 20: Pandas — Series & DataFrame Fundamentals

In [40]:
import pandas as pd

# Creating a DataFrame from a Python dictionary
data = {
    "Player": ["Saka", "Salah", "Rodrygo", "Palmer"],  # Name column
    "Position": ["RW", "RW", "RW", "RW"],  # Right Winger position
    "Goals": [16, 19, 10, 22],  # Total goals scored
    "Assists": [9, 10, 5, 11],  # Total assists provided
}

df = pd.DataFrame(data)  # Convert dictionary to DataFrame
print(df)

    Player Position  Goals  Assists
0     Saka       RW     16        9
1    Salah       RW     19       10
2  Rodrygo       RW     10        5
3   Palmer       RW     22       11

In [41]:
# 1. Exploring attributes (No parentheses needed for attributes!)
print(df.shape)

(4, 4)

In [42]:
print(df.columns)

Index(['Player', 'Position', 'Goals', 'Assists'], dtype='object')

In [43]:
print(df.dtypes)

Player      object
Position    object
Goals        int64
Assists      int64
dtype: object

In [44]:
# 2. Selecting a single column (returns a Series)
goals_series = df["Goals"]
print(goals_series)

0    16
1    19
2    10
3    22
Name: Goals, dtype: int64

In [45]:
# 3. Selecting multiple columns (returns a DataFrame)
stats = df[["Player","Goals","Assists"]]
print(stats)

    Player  Goals  Assists
0     Saka     16        9
1    Salah     19       10
2  Rodrygo     10        5
3   Palmer     22       11

In [8]:
# 4. Selecting rows by integer index using .iloc (Integer Location)
first_two_player = df.iloc[0:2]
print(first_two_player)

  Player Position  Goals  Assists
0   Saka       RW     16        9
1  Salah       RW     19       10

In [9]:
# 5. Selecting rows by condition using .loc (Label Location)
top_scorers = df.loc[df['Goals']>17,["Player","Goals"]]
print(top_scorers)

   Player  Goals
1   Salah     19
3  Palmer     22

☕ Day 21: Pandas — Cleaning: Missing Values & Duplicates

In [46]:
import numpy as np
import pandas as pd

coffee_data = {
    "Order_ID": [101, 102, 102, 103, 104, 105],  # Notice 102 is duplicated
    "Item": ["Espresso", "Latte", "Latte", "Cappuccino", np.nan, "Mocha"],  # NaN item
    "Price": [3.0, 4.5, 4.5, np.nan, 3.5, 4.0],  # NaN price
    "Quantity": [1, 2, 2, 1, 3, 1],
}

df_coffee = pd.DataFrame(coffee_data)

In [11]:
# 1. Detecting missing values
missing_counts = df_coffee.isnull().sum()
print(missing_counts)

Order_ID    0
Item        1
Price       1
Quantity    0
dtype: int64

In [12]:
# 2. Dropping rows with missing values
df_dropped = df_coffee.dropna(subset=['Item','Price'])
print(df_dropped)

   Order_ID      Item  Price  Quantity
0       101  Espresso    3.0         1
1       102     Latte    4.5         2
2       102     Latte    4.5         2
5       105     Mocha    4.0         1

In [13]:
# 3. Filling missing values (Imputation)
avg_price = df_coffee['Price'].mean()
print(avg_price)

3.9

In [14]:
df_coffee['Price'] = df_coffee['Price'].fillna(avg_price)
print(df_coffee)

   Order_ID        Item  Price  Quantity
0       101    Espresso    3.0         1
1       102       Latte    4.5         2
2       102       Latte    4.5         2
3       103  Cappuccino    3.9         1
4       104         NaN    3.5         3
5       105       Mocha    4.0         1

In [15]:
# 4. Detecting and dropping duplicates
dups = df_coffee.duplicated()
print(dups)

0    False
1    False
2     True
3    False
4    False
5    False
dtype: bool

In [16]:
# Anatomy: df.drop_duplicates(subset=[cols], keep='first', inplace=False)
df_clean = df_coffee.drop_duplicates(keep="first")
print(df_clean)

   Order_ID        Item  Price  Quantity
0       101    Espresso    3.0         1
1       102       Latte    4.5         2
3       103  Cappuccino    3.9         1
4       104         NaN    3.5         3
5       105       Mocha    4.0         1

🎓 Day 22: Pandas — Data Types & Type Conversion

In [17]:
student_data = {
    "Student_ID": ["S1", "S2", "S3", "S4"],
    "Score": [
        "85",
        "90",
        "Missing",
        "78",
    ],  # Numbers stored as strings, one text error
    "Exam_Date": ["2026-03-01", "2026-03-02", "2026-03-02", "2026-03-03"],  # Dates as strings
    "Passed": ["1", "1", "0", "1"],  # Integers stored as strings
}

df_students = pd.DataFrame(student_data)
print(df_students.dtypes)  # Everything is currently stored as 'object'!

Student_ID    object
Score         object
Exam_Date     object
Passed        object
dtype: object

In [18]:
# 1. Converting text to numeric values
df_students['Score'] = pd.to_numeric(df_students['Score'],errors="coerce")
print(df_students.dtypes)

Student_ID     object
Score         float64
Exam_Date      object
Passed         object
dtype: object

In [19]:
# 2. Converting strings to standard datetime objects
df_students['Exam_Date'] = pd.to_datetime(df_students['Exam_Date'])
df_students.dtypes

Student_ID            object
Score                float64
Exam_Date     datetime64[ns]
Passed                object
dtype: object

In [20]:
# 3. Casting data types using .astype()
df_students['Passed'] = df_students['Passed'].astype(int)
df_students.dtypes

Student_ID            object
Score                float64
Exam_Date     datetime64[ns]
Passed                 int64
dtype: object

In [21]:
df_students['Student_ID'] = df_students['Student_ID'].astype("category")
df_students.dtypes

Student_ID          category
Score                float64
Exam_Date     datetime64[ns]
Passed                 int64
dtype: object

🛒 Day 23: Pandas — GroupBy & Aggregation

In [22]:
sales_data = {
    "Category": ["Electronics", "Clothing", "Electronics", "Clothing", "Electronics", "Clothing"],
    "Region": ["North", "North", "South", "South", "North", "South"],
    "Price": [500, 50, 800, 60, 300, 40],
    "Quantity": [2, 5, 1, 10, 3, 8],
}

df_sales = pd.DataFrame(sales_data)
# Create a total revenue column for our calculations
df_sales["Revenue"] = df_sales["Price"] * df_sales["Quantity"]
df_sales

      Category Region  Price  Quantity  Revenue
0  Electronics  North    500         2     1000
1     Clothing  North     50         5      250
2  Electronics  South    800         1      800
3     Clothing  South     60        10      600
4  Electronics  North    300         3      900
5     Clothing  South     40         8      320

In [23]:
# 1. Single aggregation on a single grouped column
cat_revenue = df_sales.groupby("Category")['Revenue'].sum()
print(cat_revenue)

Category
Clothing       1170
Electronics    2700
Name: Revenue, dtype: int64

In [24]:
# 2. Multi-column grouping with multiple aggregations
multi_group = df_sales.groupby(["Category","Region"]).agg({
    "Revenue" : ["sum","mean"] ,
    "Quantity" : "sum"
})
print(multi_group)

                   Revenue        Quantity
                       sum   mean      sum
Category    Region
Clothing    North      250  250.0        5
            South      920  460.0       18
Electronics North     1900  950.0        5
            South      800  800.0        1

In [25]:
# 3. Named aggregations (The clean, modern industry standard)
top_categories = df_sales.groupby("Category").agg(
    Total_Revenue=("Revenue","sum") ,
    Avg_price=("Price","mean") ,
    Total_Units=("Quantity","sum")
).sort_values("Total_Revenue",ascending=False)
print(top_categories)

             Total_Revenue   Avg_price  Total_Units
Category
Electronics           2700  533.333333            6
Clothing              1170   50.000000           23

🔗 Day 24: Pandas — Merge, Join & Concat

In [26]:
# Table 1: Customers
customers = pd.DataFrame(
    {"Customer_ID": [1, 2, 3], "Name": ["Ali", "Bilal", "Hamza"]}
)

# Table 2: Orders (Notice Customer_ID 4 does not exist in Customers table!)
orders = pd.DataFrame(
    {
        "Order_ID": [101, 102, 103, 104],
        "Customer_ID": [1, 2, 1, 4],
        "Product_ID": ["P1", "P2", "P1", "P3"],
    }
)

# Table 3: Products
products = pd.DataFrame(
    {"Product_ID": ["P1", "P2", "P3"], "Price": [1000, 500, 200]}
)

In [27]:
# 1. Inner Join: Keeps ONLY matching rows in both tables
inner_merge = pd.merge(customers , orders , on="Customer_ID" , how="inner")
print(inner_merge)

   Customer_ID   Name  Order_ID Product_ID
0            1    Ali       101         P1
1            1    Ali       103         P1
2            2  Bilal       102         P2

In [28]:
# 2. Left Join: Keeps ALL rows from the left table, fills NaN for missing matches
left_merge = pd.merge(customers , orders , on="Customer_ID" , how="left")
print(left_merge)

   Customer_ID   Name  Order_ID Product_ID
0            1    Ali     101.0         P1
1            1    Ali     103.0         P1
2            2  Bilal     102.0         P2
3            3  Hamza       NaN        NaN

In [29]:
# 3. Three-Table Join Chain
full_pipeline = customers.merge(orders, on="Customer_ID", how="inner").merge(
    products, on="Product_ID", how="left"
)
print(full_pipeline)

   Customer_ID   Name  Order_ID Product_ID  Price
0            1    Ali       101         P1   1000
1            1    Ali       103         P1   1000
2            2  Bilal       102         P2    500

In [30]:
# 4. Vertical Concatenation: Stacking DataFrames on top of each other
new_customers = pd.DataFrame({
    "Customer_ID" : [4,5] ,
    "Name" : ["Shafi","Shafay"]
})
all_customers = pd.concat([customers , new_customers],ignore_index=True)
print(all_customers)

   Customer_ID    Name
0            1     Ali
1            2   Bilal
2            3   Hamza
3            4   Shafi
4            5  Shafay

🔤 Day 25: Pandas — Apply, Map, Lambda & String Operations

In [31]:
emp_data = {
    "Emp_ID": [101, 102, 103, 104],
    "Name": [
        "  JOHN DOE  ",
        "sarah connor",
        "Bruce Wayne",
        "clark KENT  ",
    ],  # Messy spacing & case
    "Dept_Code": ["ENG", "HR", "ENG", "MKT"],
    "Salary": [80000, 65000, 95000, 70000],
}

df_emp = pd.DataFrame(emp_data)

In [32]:
# 1. Core String Operations using .str accessor
df_emp['Name_Clean'] = df_emp['Name'].str.strip().str.title()
print(df_emp)

   Emp_ID          Name Dept_Code  Salary    Name_Clean
0     101    JOHN DOE         ENG   80000      John Doe
1     102  sarah connor        HR   65000  Sarah Connor
2     103   Bruce Wayne       ENG   95000   Bruce Wayne
3     104  clark KENT         MKT   70000    Clark Kent

In [33]:
df_emp['Is_engineering'] = df_emp['Dept_Code'].str.contains('ENG')
print(df_emp)

   Emp_ID          Name Dept_Code  Salary    Name_Clean  Is_engineering
0     101    JOHN DOE         ENG   80000      John Doe            True
1     102  sarah connor        HR   65000  Sarah Connor           False
2     103   Bruce Wayne       ENG   95000   Bruce Wayne            True
3     104  clark KENT         MKT   70000    Clark Kent           False

In [34]:
# 2. Value replacement using .map()
dept_names = {"ENG":"Engineering","HR":"Human Resources","MKT":"Marketing"}
df_emp['Department'] = df_emp['Dept_Code'].map(dept_names)
print(df_emp)

   Emp_ID          Name Dept_Code  Salary    Name_Clean  Is_engineering  \
0     101    JOHN DOE         ENG   80000      John Doe            True
1     102  sarah connor        HR   65000  Sarah Connor           False
2     103   Bruce Wayne       ENG   95000   Bruce Wayne            True
3     104  clark KENT         MKT   70000    Clark Kent           False

        Department
0      Engineering
1  Human Resources
2      Engineering
3        Marketing

In [35]:
# 3. Custom logic across a single column using .apply() and lambda
df_emp['Bonus'] = df_emp['Salary'].apply(
    lambda x : x * 0.10 if x < 75000 else x * 0.05
)
print(df_emp)

   Emp_ID          Name Dept_Code  Salary    Name_Clean  Is_engineering  \
0     101    JOHN DOE         ENG   80000      John Doe            True
1     102  sarah connor        HR   65000  Sarah Connor           False
2     103   Bruce Wayne       ENG   95000   Bruce Wayne            True
3     104  clark KENT         MKT   70000    Clark Kent           False

        Department   Bonus
0      Engineering  4000.0
1  Human Resources  6500.0
2      Engineering  4750.0
3        Marketing  7000.0

In [36]:
# 4. Row-level calculations across multiple columns (axis=1)
df_emp["Total_Compensation"] = df_emp.apply(
    lambda row: row["Salary"] + row["Bonus"], axis=1
)

print(df_emp[["Name_Clean", "Department", "Total_Compensation"]])

     Name_Clean       Department  Total_Compensation
0      John Doe      Engineering             84000.0
1  Sarah Connor  Human Resources             71500.0
2   Bruce Wayne      Engineering             99750.0
3    Clark Kent        Marketing             77000.0

📊 Day 26: Pandas — Sorting, Ranking, Rolling & Pivot Tables

In [37]:
revenue_data = {
    "Date": pd.to_datetime(
        [
            "2026-07-01",
            "2026-07-02",
            "2026-07-03",
            "2026-07-04",
            "2026-07-01",
            "2026-07-02",
            "2026-07-03",
            "2026-07-04",
        ]
    ),
    "Store": [
        "Lahore",
        "Lahore",
        "Lahore",
        "Lahore",
        "Karachi",
        "Karachi",
        "Karachi",
        "Karachi",
    ],
    "Revenue": [100, 150, 130, 200, 300, 280, 350, 400],
}

df_rev = pd.DataFrame(revenue_data)

In [38]:
# 1. Sorting by columns
df_sorted = df_rev.sort_values(["Store","Date"],ascending=[True,True])
print(df_sorted)

        Date    Store  Revenue
4 2026-07-01  Karachi      300
5 2026-07-02  Karachi      280
6 2026-07-03  Karachi      350
7 2026-07-04  Karachi      400
0 2026-07-01   Lahore      100
1 2026-07-02   Lahore      150
2 2026-07-03   Lahore      130
3 2026-07-04   Lahore      200

In [39]:
# 2. Ranking values within groups
df_rev["Revenue_Rank"] = df_rev.groupby("Store")["Revenue"].rank(
    method="dense" , ascending=False
)
print(df_sorted)

        Date    Store  Revenue
4 2026-07-01  Karachi      300
5 2026-07-02  Karachi      280
6 2026-07-03  Karachi      350
7 2026-07-04  Karachi      400
0 2026-07-01   Lahore      100
1 2026-07-02   Lahore      150
2 2026-07-03   Lahore      130
3 2026-07-04   Lahore      200

In [49]:
# 3. Rolling Window (Moving Average for Feature Engineering)
df_rev["2_Day_MA"] = (
    df_rev.groupby("Store")["Revenue"]
    .rolling(window=2)
    .mean()
    .reset_index(level=0, drop=True)
)
print(df_rev["2_Day_MA"])

0      NaN
1    125.0
2    140.0
3    165.0
4      NaN
5    290.0
6    315.0
7    375.0
Name: 2_Day_MA, dtype: float64

In [50]:
pivot_report = pd.pivot_table(
    df_rev,
    values="Revenue",  # The numbers to aggregate
    index="Date",  # Rows of the pivot table
    columns="Store",  # Columns of the pivot table
    aggfunc="sum",  # Aggregation function
)

print(pivot_report)

Store       Karachi  Lahore
Date
2026-07-01      300     100
2026-07-02      280     150
2026-07-03      350     130
2026-07-04      400     200